spring:
  datasource:
    url: jdbc:mysql://frps.zxl78585.com:3306/newideas?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: xslgy
    password: e9d7898c-5212-42c9-9047-b092b09faacd
newIdeas:
  cdnUrl: http://localhost
  filePath: d:/test
  rsaDecodeUrl: http://frps.zxl78585.com:89
  defaultAdminPassword: 123456
  sms:
    accessKeyId: LTAIkr87bqlh9YCj
    accessSecret: 40P10gM1AVdNsqqpS6RqMSo8aENAh9
    sign: 赵新乐
